"""decouple platform from bot definition

Revision ID: a88f6010bc53
Revises: 7b609653a068
Create Date: 2016-10-10 09:55:43.006537

"""

# revision identifiers, used by Alembic.
revision = 'a88f6010bc53'
down_revision = '7b609653a068'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    op.add_column('bot', sa.Column('settings', sa.PickleType(), nullable=True))
    op.add_column('platform', sa.Column('deployed', sa.Boolean(),
                  nullable=False, default=False))
    op.alter_column('platform', 'bot_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform', 'bot_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.drop_column('platform', 'deployed')
    op.drop_column('bot', 'settings')
