#!/usr/bin/python
# -*- coding: utf-8 -*-

data = {
    '聯博全球高收益債券基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/gershon.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Global-High-Yield.htm?ShareClassId=68035586',
        'desc': '本基金投資於世界各地機構發行的高收益債券，包括美國及新興國家，以追求高度的經常收入及資本增值潛力。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博美國收益基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/Matthew.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/American-Income.htm?ShareClassId=60006908',
        'desc': '本基金主要分散投資於美元債券，以提供較高收益以及追求資本增值的潛力。本基金投資於美國境內外註冊之高評級和高收益的債券。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博聚焦美國股票基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/james.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Concentrated-US.htm?ShareClassId=68243444',
        'desc': '本基金透過投資於優質的美國成長公司股票，建構主動式管理及聚焦的投資組合，尋求長線資本增值。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博歐洲收益基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/ScottDiMaggio.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/European-Income.htm?ShareClassId=60012954',
        'desc': '本基金分散投資於以歐元或歐洲貨幣計價之投資等級或非投資等級固定收益證券，以追求高度的報酬與資本增值潛力。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博新興市場多元收益基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/morgan.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Emerging-Markets-Multi-Asset.htm?ShareClassId=68105570',
        'desc': '本基金以追求最佳總報酬為目標。透過佈局新興市場多元資產，為投資人尋求長期資本增值及較低波動。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博日本策略價值基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/Katsuaki.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Japan-Strategic-Value.htm?ShareClassId=68061502',
        'desc': '本基金投資於基金經理團隊認為股票評價被低估的日本股票之投資組合，以尋求長期資本增值。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博美國成長基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/frank.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/American-Growth.htm?ShareClassId=60006906',
        'desc': '本基金投資於美國發行之大型股票證券，以追求長期資本增值。本基金主要投資於優質且基礎穩固的美國公司。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博歐洲成長基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/tawhid.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/European-Value.htm?ShareClassId=60060103',
        'desc': '本基金以追求長期資本增值為投資目標。在任何市況下，預期基金將至少80%總資產投資於設立在歐洲，或主要在歐洲營運之公司股票。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博新興市場成長基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/Sergey.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Emerging-Markets-Growth.htm?ShareClassId=68052644',
        'desc': '本基金投資於全球具成長潛力之新興市場股票。尋找扎實、有持久成長潛力及擁有強勁競爭優勢之企業，並投資於擁有高投入資本回報及強勁自由現金流量之企業。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博歐洲價值型基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/tawhid.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Eurozone-Strategic-Value.htm?ShareClassId=68061762',
        'desc': '本基金以追求長期資本增值為投資目標。在任何市況下，預期基金將至少80%總資產投資於設立在歐元區，或主要在歐元區營運之公司股票。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博全球平衡型基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/avi.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Global-Equity-Blend.htm?ShareClassId=60093187',
        'desc': '本基金投資於股票證券，以追求長期資本增值。本基金是為追求股票報酬的投資者而設計的，而此類投資者也希望廣泛分散不同型態、市值和地域所造成的相關投資風險。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博中國時機基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/stuart.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Greater-China.htm?ShareClassId=60000216',
        'desc': '本基金主要投資於中國企業，以尋求長期資本增值。投資團隊將審慎評估經濟與政治前景、特定證券相對其他標的之投資價值、企業獲利趨勢、以及管理階層的經營能力。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博全球複合型股票基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/danielr.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Global-Equity-Blend.htm?ShareClassId=60093187',
        'desc': '本基金投資於股票證券，以追求長期資本增值。本基金是為追求股票報酬的投資者而設計的，而此類投資者也希望廣泛分散不同型態、市值和地域所造成的相關投資風險。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博全球前瞻主題基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/danielr.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Thematic-Research.htm?ShareClassId=68052594',
        'desc': '本基金投資於全球各種產業中，受益於創新發展的公司，以追求長期資本增值，並發掘成長機會。基金經理採用由上而下的研究方法，尋找具長期成長潛力並將驅動跨產業市場的投資主題',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博全球價值型基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/tawhid.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Global-Value.htm?ShareClassId=68052624',
        'desc': '本基金投資於基金經理判定為被市場低估的全球股票證券，以追求長期資本增值。基金經理公司結合基本面研究投資法與紀律化的投資程序以評估投資對象的潛在價值。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博房貸收益基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/michaels.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Mortgage-Income.htm?ShareClassId=60060089',
        'desc': '本基金追求較高的風險調整後總報酬。投資組合可布局於投資等級及非投資等級之房貸相關證券及其他資產擔保證券，且投資組合至少2/3的資產將會投資於房貸相關證券。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博亞洲股票基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/stuart.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/Asia-ex-Japan-Equity.htm?ShareClassId=68035833',
        'desc': '本基金運用基本面與量化投資流程，判斷預估報酬率，以尋求價格被低估之股票和其可能帶來之超額報酬潛力。透過縝密的研究，於亞洲地區（日本以外）挑選約60至100檔具有長期獲利潛力，且價格出現折價的股票。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博印度成長基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/Sergey.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/India-Growth.htm?ShareClassId=68013272',
        'desc': '本基金主要投資於印度股票及股權相關證券，以達到長期資本增值之目的。本基金的投資對象為受惠於印度開放經濟所帶來的快速成長，並能展現其良好的能力適應新環境所帶來之挑戰，但短期內因部份因素導致股價遭低估之公司。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
    '聯博國際醫療基金': {
        'image_url': 'https://www.abfunds.com.tw/APAC/TW/Biographies/Images/Sergey.jpg',
        'item_url': 'https://www.abfunds.com.tw/APAC/TW/Funds/International-Health-Care.htm?ShareClassId=60000206',
        'desc': '本基金透過投資於全球經營健康護理及衛生科學行業相關之股票，以尋求資本增值。基金大部分投資於美國公司。',
        'net_worth_url': 'https://yjlou-backup.appspot.com/s/img/net_worth.png',
        'channel': '華南銀行，永豐金，臺灣銀行',
        'sales_url': 'https://yjlou-backup.appspot.com/s/img/sales.jpg',
    },
}
